# Generated by Django 4.0.2 on 2022-03-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdepartment',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
