# Generated by Django 4.0.2 on 2022-03-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0004_businesses'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesses',
            name='name',
            field=models.CharField(default='max', max_length=30),
        ),
    ]
