# Generated by Django 4.0.2 on 2022-03-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0006_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupants',
            name='name',
            field=models.CharField(default='Ru', max_length=30),
        ),
    ]
